[package]
name = "fixed-revision"
version = "0.1.0"
edition = "2021"

[dependencies]
fixed-type-id = { path = "../fixed_type_id", version = "0.1.2" }
serde = "1.0.216"

[dev-dependencies]
serde-hjson = "1.1.0"
serde_json = "1.0.133"
toml = "0.8.19"
ron = "0.8.1"
